config/routes.rb
Rails.application.routes.draw do
  root "parkings#index"

  resources :parkings do
    resources :entry_points, only: [:new, :edit, :create, :update]
    resources :spots, only: [:new, :edit, :create, :update]
    resources :tickets, only: [:new, :create, :edit, :update]
  end

  resources :cars, only: [:index, :show]
  resources :tickets, only: [:index, :show]
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :parking

  has_many :tickets
  has_and_belongs_to_many :entry_points
  # has_and_belongs_to_many :nearby_entry_points, join_table: :entry_points_spots

  validates :number, presence: true
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :find_parking

  # def index
  #   @spots = @parking.spots
  # end

  # def show
  #   @spot = @parking.spots.find(params[:id])
  # end

  def new
    @spot = @parking.spots.new
  end

  def create
    @spot = @parking.spots.new(spot_params)
    respond_to do |format|
      if @spot.save
        format.html { redirect_to parking_url(@parking), notice: "Spot was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @spot = @parking.spots.find(params[:id])
  end

  def update
    @spot = @parking.spots.find(params[:id])

    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to parking_url(@parking), notice: "Spot was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_parking
    @parking = Parking.find(params[:parking_id])
  end

  def spot_params
    params.require(:spot).permit(:number, entry_point_ids: [])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_with(model: [@parking, spot]) do |form| %>
  <% if spot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>
  <div>
    <%= form.label :entry_point_ids, "Select nearby Entry Points", style: "display: block" %>
    <%= form.collection_check_boxes :entry_point_ids, @parking.entry_points, :id, :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render "form", spot: @spot %>

<br>

<div>
  <%= link_to "Back to parking lot", parking_path(@parking) %>|
</div>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render "form", spot: @spot %>

<br>

<div>
  <%= link_to "Back to parking lot", parking_path(@parking) %>
</div>