config/routes.rb
Rails.application.routes.draw do
  root "parkings#index"

  resources :parkings do
    resources :entry_points, only: [:new, :edit, :create, :update]
    resources :spots, only: [:new, :edit, :create, :update]
    resources :tickets, only: [:new, :create, :edit, :update]
  end

  resources :cars, only: [:index, :show]
  resources :tickets, only: [:index, :show]
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :parking
  belongs_to :entry_point
  belongs_to :spot
  belongs_to :car

  accepts_nested_attributes_for :car
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.includes(:car, :parking, :spot, :entry_point).order(id: :desc)
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @parking = Parking.find(params[:parking_id])
    @ticket = @parking.tickets.new
    @ticket.build_car
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @parking = Parking.find(params[:parking_id])
    @ticket = @parking.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @parking = @ticket.parking
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:entry_point_id, :spot_id, car_attributes: [:id, :color, :registration_number])
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: [@parking, ticket]) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :entry_point_id, "Select Entry Point", style: "display: block" %>
    <%= form.select :entry_point_id, options_from_collection_for_select(@parking.entry_points, :id, :number) %>
  </div>

  <div>
    <%= form.label :spot_id, "Select Entry Point", style: "display: block" %>
    <%= form.select :spot_id, options_from_collection_for_select(@parking.spots, :id, :number) %>
  </div>

  <div>
    <%= form.fields_for :car do |cf| %>
      <div>
        <%= cf.label :registration_number, style: "display: block" %>
        <%= cf.text_field :registration_number %>
      </div>
      <div>
        <%= cf.label :color, style: "display: block" %>
        <%= cf.text_field :color %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p><b>Ticket Number:</b> <%= ticket.id %></p>
  <p><b>Car:</b> <%= ticket.car&.registration_number %></p>
  <p><b>Parking Lot: </b> <%= ticket.parking.name %></p>
  <p><b>Entry:</b> <%= ticket.entry_point.number %></p>
  <p><b>Spot:</b> <%= ticket.spot.number %></p>
</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to parkings", parkings_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <table>
    <tr>
      <th>Ticket Number</th>
      <th>Car R.No.</th>
      <th>Car Color</th>
      <th>Parking</th>
      <th>Entry</th>
      <th>Spot</th>
      <th></th>
    </tr>
    <% @tickets.each do |ticket| %>
    <tr id="<%= dom_id ticket %>">
      <td><%= ticket.id %></td>
      <td><%= ticket.car.registration_number %></td>
      <td><%= ticket.car.color %></td>
      <td><%= ticket.parking.name %></td>
      <td><%= ticket.entry_point.number %></td>
      <td><%= ticket.spot.number %></td>
      <td>
        <%= link_to "Show this ticket", ticket %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to parkings", parkings_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Edit this ticket", edit_parking_ticket_path(@parking, @ticket) %> |
  <%= link_to "Back to tickets", tickets_path %>

  <%= button_to "Destroy this ticket", @ticket, method: :delete %>
</div>