config/routes.rb
Rails.application.routes.draw do
  root "parkings#index"

  resources :parkings do
    resources :entry_points, only: [:new, :edit, :create, :update]
    resources :spots, only: [:new, :edit, :create, :update]
    resources :tickets, only: [:new, :create, :edit, :update]
  end

  resources :cars, only: [:index, :show]
  resources :tickets, only: [:index, :show]
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :entry_points, dependent: :delete_all
  has_many :spots, dependent: :delete_all
  has_many :tickets, dependent: :delete_all

  validates :number, :name, :location, presence: true
  validates :number, uniqueness: true
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: %i[ show edit update destroy ]

  # GET /parkings or /parkings.json
  def index
    @parkings = Parking.all
  end

  # GET /parkings/1 or /parkings/1.json
  def show
  end

  # GET /parkings/new
  def new
    @parking = Parking.new
  end

  # GET /parkings/1/edit
  def edit
  end

  # POST /parkings or /parkings.json
  def create
    @parking = Parking.new(parking_params)

    respond_to do |format|
      if @parking.save
        format.html { redirect_to parking_url(@parking), notice: "Parking was successfully created." }
        format.json { render :show, status: :created, location: @parking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parkings/1 or /parkings/1.json
  def update
    respond_to do |format|
      if @parking.update(parking_params)
        format.html { redirect_to parking_url(@parking), notice: "Parking was successfully updated." }
        format.json { render :show, status: :ok, location: @parking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1 or /parkings/1.json
  def destroy
    @parking.destroy

    respond_to do |format|
      format.html { redirect_to parkings_url, notice: "Parking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking
      @parking = Parking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parking_params
      params.require(:parking).permit(:name, :number, :location)
    end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/_form.html.erb
<%= form_with(model: parking) do |form| %>
  <% if parking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(parking.errors.count, "error") %> prohibited this parking from being saved:</h2>

      <ul>
        <% parking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_area :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parkings/_parking.html.erb
<div id="<%= dom_id parking %>">
  <p>
    <strong>Name:</strong>
    <%= parking.name %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= parking.number %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= parking.location %>
  </p>

</div>

app/views/parkings/edit.html.erb
<h1>Editing parking</h1>

<%= render "form", parking: @parking %>

<br>

<div>
  <%= link_to "Show this parking", @parking %> |
  <%= link_to "Back to parkings", parkings_path %>
</div>

app/views/parkings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parkings</h1>
<b><%= link_to "New parking", new_parking_path %></b>

<div id="parkings">
  <% @parkings.each do |parking| %>
    <%= render parking %>
    <p>
      <%= link_to "Show this parking", parking %>
    </p>
  <% end %>
</div>

app/views/parkings/new.html.erb
<h1>New parking</h1>

<%= render "form", parking: @parking %>

<br>

<div>
  <%= link_to "Back to parkings", parkings_path %>
</div>

app/views/parkings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @parking %>

<div>
  <%= link_to "Edit this parking", edit_parking_path(@parking) %> |
  <%= link_to "Add Entry Point", new_parking_entry_point_path(@parking) %> |
  <%= link_to "Add Spot", new_parking_spot_path(@parking) %> |
  <%= link_to "New ticket", new_parking_ticket_path(@parking), style: "color: red;" %> |
  <%= link_to "Back to parkings", parkings_path %>
</div>

<hr>

<div>
  <% if @parking.entry_points.present? %>
    <p>Entry Points</p>
    <ul>
      <% @parking.entry_points.each do |entry_point| %>
        <li>
          <%= entry_point.number %> |
          <%= link_to "edit", edit_parking_entry_point_path(@parking, entry_point) %>
        </li>
      <% end %>
    </ul>
  <% else %>
  <p style="color: red;">Please add atleast one entry point.</p>
  <% end %>
</div>

<hr>

<div>
  <%= link_to "Add Spot", new_parking_spot_path(@parking) %>
  <% if @parking.spots.present? %>
    <p>Spots</p>
    <ul>
      <% @parking.spots.each do |spot| %>
        <li>
          <%= spot.number %> |
          <%= link_to "edit", edit_parking_spot_path(@parking, spot) %>
        </li>
      <% end %>
    </ul>
  <% else %>
  <p style="color: red;">Please add parking spot here.</p>
  <% end %>
</div>

<hr>
<p><%= button_to "Destroy this parking lot", @parking, method: :delete %></p>