config/routes.rb
Rails.application.routes.draw do
  root "parkings#index"

  resources :parkings do
    resources :entry_points, only: [:new, :edit, :create, :update]
    resources :spots, only: [:new, :edit, :create, :update]
    resources :tickets, only: [:new, :create, :edit, :update]
  end

  resources :cars, only: [:index, :show]
  resources :tickets, only: [:index, :show]
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :tickets

  validates :registration_number, presence: true
  validates :color, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    params[:search] ||= {}
    if color = params[:search][:color]
      @cars = Car.where(color: color.strip)
    else
      @cars = Car.all
    end
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  # def new
  #   @car = Car.new
  # end

  # # GET /cars/1/edit
  # def edit
  # end

  # # POST /cars or /cars.json
  # def create
  #   @car = Car.new(car_params)

  #   respond_to do |format|
  #     if @car.save
  #       format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
  #       format.json { render :show, status: :created, location: @car }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @car.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /cars/1 or /cars/1.json
  # def update
  #   respond_to do |format|
  #     if @car.update(car_params)
  #       format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
  #       format.json { render :show, status: :ok, location: @car }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @car.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /cars/1 or /cars/1.json
  # def destroy
  #   @car.destroy

  #   respond_to do |format|
  #     format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def car_params
    #   params.require(:car).permit(:registration_number, :color)
    # end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Registration number:</strong>
    <%= car.registration_number %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :registration_number, style: "display: block" %>
    <%= form.text_field :registration_number %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars</h1>
<%= form_for :search, url: cars_path, method: :get do |form| %>
  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.submit "Search" %>
  </div>
<% end %>

<p></p>
<div id="cars">
  <table>
    <tr>
      <th>Registration. No.</th>
      <th>Color</th>
      <th></th>
    </tr>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.registration_number %></td>
        <td><%= car.color %></td>
        <td><%= link_to "Show", car %></td>
      </tr>
    <% end %>
  </table>
</div>

<%#= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%#= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%#= button_to "Destroy this car", @car, method: :delete %>
</div>